# This workflow will create a new release when a version tag is pushed
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Create Release

on:
  push:
    tags:
      - 'v*' # Run when tag matches v*, e.g., v1.0.0

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v

  create-release:
    needs: build-and-test
    runs-on: macos-latest
    permissions:
      contents: write # Needed for creating releases
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create application bundle
      run: |
        chmod +x ./build-spm.sh
        ./build-spm.sh
    
    - name: Create ZIP archive
      run: |
        zip -r CentralTime-${{ steps.get_version.outputs.VERSION }}.zip CentralTime.app
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          CentralTime-${{ steps.get_version.outputs.VERSION }}.zip
          VERSION
        body: |
          # CentralTime ${{ steps.get_version.outputs.VERSION }}
          
          A Swift menubar app that cycles through and displays time in multiple cities.
          
          ## What's New in 2.0.0
          
          ### 🎨 **Complete UI Redesign**
          - Modern SwiftUI interface with clean, single-line city displays
          - Dynamic menu bar text showing current city emoji, code, and time
          - Proper status bar implementation using NSStatusItem + NSPopover
          
          ### 🌍 **Enhanced City Management**
          - Cities now sorted by timezone offset (west to east)
          - Improved city selection interface with search functionality
          - Fixed duplicate city issues - each city appears only once
          - Better timezone data management using Swift's built-in TimeZone APIs
          
          ### ⚙️ **Better Settings Experience**
          - Fixed settings window sizing and positioning
          - Proper window management - Cancel/Save buttons no longer close the app
          - Settings window can be reopened without conflicts
          
          ### 🔧 **Technical Improvements**
          - Replaced hardcoded timezone data with dynamic TimeZoneManager
          - Better error handling and window lifecycle management
          - Improved code organization and maintainability
          
          ## Installation
          
          1. Download the CentralTime-${{ steps.get_version.outputs.VERSION }}.zip file
          2. Unzip the file
          3. Move CentralTime.app to your Applications folder
          4. Open the application
          
          ## System Requirements
          
          - macOS 13.0 (Ventura) or later
          - Tested on macOS Sonoma and Sequoia