name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Build Debug
      run: |
        chmod +x ./build.sh
        ./build.sh --type development
    
    - name: Build Release
      run: ./build.sh --type release
    
    - name: Run tests (if any)
      run: swift test -v || echo "No tests found, continuing..."
    
    - name: Verify app bundle
      run: |
        if [ ! -d "CentralTime.app" ]; then
          echo "Error: App bundle not created"
          exit 1
        fi
        echo "App bundle created successfully"
        ls -la CentralTime.app/Contents/MacOS/
